/*
 * Created on 3 Apr 2016 ( Time 21:14:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.tsm.project.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "customer"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="customer", schema="main" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Customer.countAll", query="SELECT COUNT(x) FROM Customer x" )
} )
public class Customer implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="cust_title", length=10)
    private String     custTitle    ;

    @Column(name="cust_code", length=10)
    private String     custCode     ;

    @Column(name="cust_name", length=40)
    private String     custName     ;

    @Column(name="cust_phone", length=10)
    private String     custPhone    ;

    @Column(name="cust_fax", length=12)
    private String     custFax      ;

    @Column(name="cust_desc", length=100)
    private String     custDesc     ;

    @Column(name="created_by", length=20)
    private String     createdBy    ;

    @Temporal(TemporalType.DATE)
    @Column(name="created_date")
    private Date       createdDate  ;

    @Column(name="updated_by", length=20)
    private String     updatedBy    ;

    @Temporal(TemporalType.DATE)
    @Column(name="updated_date")
    private Date       updatedDate  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Customer()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : cust_title ( bpchar ) 
    public void setCustTitle( String custTitle )
    {
        this.custTitle = custTitle;
    }
    public String getCustTitle()
    {
        return this.custTitle;
    }

    //--- DATABASE MAPPING : cust_code ( bpchar ) 
    public void setCustCode( String custCode )
    {
        this.custCode = custCode;
    }
    public String getCustCode()
    {
        return this.custCode;
    }

    //--- DATABASE MAPPING : cust_name ( bpchar ) 
    public void setCustName( String custName )
    {
        this.custName = custName;
    }
    public String getCustName()
    {
        return this.custName;
    }

    //--- DATABASE MAPPING : cust_phone ( bpchar ) 
    public void setCustPhone( String custPhone )
    {
        this.custPhone = custPhone;
    }
    public String getCustPhone()
    {
        return this.custPhone;
    }

    //--- DATABASE MAPPING : cust_fax ( bpchar ) 
    public void setCustFax( String custFax )
    {
        this.custFax = custFax;
    }
    public String getCustFax()
    {
        return this.custFax;
    }

    //--- DATABASE MAPPING : cust_desc ( bpchar ) 
    public void setCustDesc( String custDesc )
    {
        this.custDesc = custDesc;
    }
    public String getCustDesc()
    {
        return this.custDesc;
    }

    //--- DATABASE MAPPING : created_by ( bpchar ) 
    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }
    public String getCreatedBy()
    {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( date ) 
    public void setCreatedDate( Date createdDate )
    {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate()
    {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : updated_by ( bpchar ) 
    public void setUpdatedBy( String updatedBy )
    {
        this.updatedBy = updatedBy;
    }
    public String getUpdatedBy()
    {
        return this.updatedBy;
    }

    //--- DATABASE MAPPING : updated_date ( date ) 
    public void setUpdatedDate( Date updatedDate )
    {
        this.updatedDate = updatedDate;
    }
    public Date getUpdatedDate()
    {
        return this.updatedDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(custTitle);
        sb.append("|");
        sb.append(custCode);
        sb.append("|");
        sb.append(custName);
        sb.append("|");
        sb.append(custPhone);
        sb.append("|");
        sb.append(custFax);
        sb.append("|");
        sb.append(custDesc);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedDate);
        return sb.toString(); 
    } 

}