package com.tsm.project.model;
// Generated Feb 13, 2016 12:49:40 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustInfo generated by hbm2java
 */
@Entity
@Table(name = "cust_info", schema = "main")
public class CustInfo implements java.io.Serializable {

	private int cusId;
	private String cusCode;
	private String cusName;
	private Integer cusPruchase;
	private String cusAddress;
	private String cusEmail;
	private Character cusPhone;
	private Character cusTel;
	private Character createBy;
	private Date createDate;
	private Character updateBy;
	private Date updateDate;

	public CustInfo() {
	}

	public CustInfo(int cusId) {
		this.cusId = cusId;
	}

	public CustInfo(int cusId, String cusCode, String cusName, Integer cusPruchase, String cusAddress, String cusEmail,
			Character cusPhone, Character cusTel, Character createBy, Date createDate, Character updateBy,
			Date updateDate) {
		this.cusId = cusId;
		this.cusCode = cusCode;
		this.cusName = cusName;
		this.cusPruchase = cusPruchase;
		this.cusAddress = cusAddress;
		this.cusEmail = cusEmail;
		this.cusPhone = cusPhone;
		this.cusTel = cusTel;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	@Id

	@Column(name = "cus_id", unique = true, nullable = false)
	public int getCusId() {
		return this.cusId;
	}

	public void setCusId(int cusId) {
		this.cusId = cusId;
	}

	@Column(name = "cus_code", length = 20)
	public String getCusCode() {
		return this.cusCode;
	}

	public void setCusCode(String cusCode) {
		this.cusCode = cusCode;
	}

	@Column(name = "cus_name", length = 100)
	public String getCusName() {
		return this.cusName;
	}

	public void setCusName(String cusName) {
		this.cusName = cusName;
	}

	@Column(name = "cus_pruchase")
	public Integer getCusPruchase() {
		return this.cusPruchase;
	}

	public void setCusPruchase(Integer cusPruchase) {
		this.cusPruchase = cusPruchase;
	}

	@Column(name = "cus_address", length = 200)
	public String getCusAddress() {
		return this.cusAddress;
	}

	public void setCusAddress(String cusAddress) {
		this.cusAddress = cusAddress;
	}

	@Column(name = "cus_email", length = 50)
	public String getCusEmail() {
		return this.cusEmail;
	}

	public void setCusEmail(String cusEmail) {
		this.cusEmail = cusEmail;
	}

	@Column(name = "cus_phone", length = 1)
	public Character getCusPhone() {
		return this.cusPhone;
	}

	public void setCusPhone(Character cusPhone) {
		this.cusPhone = cusPhone;
	}

	@Column(name = "cus_tel", length = 1)
	public Character getCusTel() {
		return this.cusTel;
	}

	public void setCusTel(Character cusTel) {
		this.cusTel = cusTel;
	}

	@Column(name = "create_by", length = 1)
	public Character getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Character createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 13)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_by", length = 1)
	public Character getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Character updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "update_date", length = 13)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
