package com.tsm.project.model;
// Generated Feb 5, 2016 2:32:06 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpInfo generated by hbm2java
 */
@Entity
@Table(name = "emp_info", schema = "main")
public class EmpInfo implements java.io.Serializable {

	private int id;
	private String empCode;
	private String empTitle;
	private String empName;
	private String empAddress;
	private String empEmail;
	private String empPhone;
	private String empFax;
	private String empDesc;
	private Integer empStatus;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private Date empDateAttended;
	private String empPosition;

	public EmpInfo() {
	}

	public EmpInfo(int id) {
		this.id = id;
	}

	public EmpInfo(int id, String empCode, String empTitle, String empName, String empAddress, String empEmail,
			String empPhone, String empFax, String empDesc, Integer empStatus, String createBy, Date createDate,
			String updateBy, Date updateDate, Date empDateAttended, String empPosition) {
		this.id = id;
		this.empCode = empCode;
		this.empTitle = empTitle;
		this.empName = empName;
		this.empAddress = empAddress;
		this.empEmail = empEmail;
		this.empPhone = empPhone;
		this.empFax = empFax;
		this.empDesc = empDesc;
		this.empStatus = empStatus;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.empDateAttended = empDateAttended;
		this.empPosition = empPosition;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "emp_code", length = 6)
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Column(name = "emp_title", length = 10)
	public String getEmpTitle() {
		return this.empTitle;
	}

	public void setEmpTitle(String empTitle) {
		this.empTitle = empTitle;
	}

	@Column(name = "emp_name", length = 50)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "emp_address", length = 100)
	public String getEmpAddress() {
		return this.empAddress;
	}

	public void setEmpAddress(String empAddress) {
		this.empAddress = empAddress;
	}

	@Column(name = "emp_email", length = 50)
	public String getEmpEmail() {
		return this.empEmail;
	}

	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail;
	}

	@Column(name = "emp_phone", length = 10)
	public String getEmpPhone() {
		return this.empPhone;
	}

	public void setEmpPhone(String empPhone) {
		this.empPhone = empPhone;
	}

	@Column(name = "emp_fax", length = 10)
	public String getEmpFax() {
		return this.empFax;
	}

	public void setEmpFax(String empFax) {
		this.empFax = empFax;
	}

	@Column(name = "emp_desc", length = 100)
	public String getEmpDesc() {
		return this.empDesc;
	}

	public void setEmpDesc(String empDesc) {
		this.empDesc = empDesc;
	}

	@Column(name = "emp_status")
	public Integer getEmpStatus() {
		return this.empStatus;
	}

	public void setEmpStatus(Integer empStatus) {
		this.empStatus = empStatus;
	}

	@Column(name = "create_by", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 13)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_by", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "update_date", length = 13)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "emp_date_attended", length = 13)
	public Date getEmpDateAttended() {
		return this.empDateAttended;
	}

	public void setEmpDateAttended(Date empDateAttended) {
		this.empDateAttended = empDateAttended;
	}

	@Column(name = "emp_position", length = 50)
	public String getEmpPosition() {
		return this.empPosition;
	}

	public void setEmpPosition(String empPosition) {
		this.empPosition = empPosition;
	}

}
