/*
 * Created on 28 Mar 2016 ( Time 19:40:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.tsm.project.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "product_type"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="product_type", schema="main" )

public class ProductType implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="create_by", length=45)
    private String     createBy     ;

    @Temporal(TemporalType.DATE)
    @Column(name="create_date")
    private Date       createDate   ;

    @Column(name="prod_code", length=45)
    private String     prodCode     ;

    @Column(name="prod_desc", length=45)
    private String     prodDesc     ;

    @Column(name="prod_name", length=45)
    private String     prodName     ;

    @Column(name="update_by", length=45)
    private String     updateBy     ;

    @Temporal(TemporalType.DATE)
    @Column(name="update_date")
    private Date       updateDate   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="productType", targetEntity=Product.class)
    private List<Product> listOfProduct;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ProductType() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : create_by ( varchar ) 
    public void setCreateBy( String createBy ) {
        this.createBy = createBy;
    }
    public String getCreateBy() {
        return this.createBy;
    }

    //--- DATABASE MAPPING : create_date ( date ) 
    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- DATABASE MAPPING : prod_code ( varchar ) 
    public void setProdCode( String prodCode ) {
        this.prodCode = prodCode;
    }
    public String getProdCode() {
        return this.prodCode;
    }

    //--- DATABASE MAPPING : prod_desc ( varchar ) 
    public void setProdDesc( String prodDesc ) {
        this.prodDesc = prodDesc;
    }
    public String getProdDesc() {
        return this.prodDesc;
    }

    //--- DATABASE MAPPING : prod_name ( varchar ) 
    public void setProdName( String prodName ) {
        this.prodName = prodName;
    }
    public String getProdName() {
        return this.prodName;
    }

    //--- DATABASE MAPPING : update_by ( varchar ) 
    public void setUpdateBy( String updateBy ) {
        this.updateBy = updateBy;
    }
    public String getUpdateBy() {
        return this.updateBy;
    }

    //--- DATABASE MAPPING : update_date ( date ) 
    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfProduct( List<Product> listOfProduct ) {
        this.listOfProduct = listOfProduct;
    }
    public List<Product> getListOfProduct() {
        return this.listOfProduct;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(createBy);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(prodCode);
        sb.append("|");
        sb.append(prodDesc);
        sb.append("|");
        sb.append(prodName);
        sb.append("|");
        sb.append(updateBy);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 

}
