/*
 * Created on 24 Mar 2016 ( Time 03:13:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.tsm.project.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "product"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="product", schema="main" )

public class Product implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="create_by", length=45)
    private String     createBy     ;

    @Temporal(TemporalType.DATE)
    @Column(name="create_date")
    private Date       createDate   ;

    @Column(name="prod_brand", length=45)
    private String     prodBrand    ;

    @Column(name="prod_code", length=45)
    private String     prodCode     ;

    @Column(name="prod_color", length=45)
    private String     prodColor    ;

    @Column(name="prod_desc", length=100)
    private String     prodDesc     ;

    @Column(name="prod_img", length=250)
    private String     prodImg      ;

    @Column(name="prod_model", length=45)
    private String     prodModel    ;

    @Column(name="prod_name", length=45)
    private String     prodName     ;

    @Column(name="prod_price")
    private Long       prodPrice    ;

    @Column(name="prod_quantity")
    private Integer    prodQuantity ;

    @Column(name="prod_status")
    private Integer    prodStatus   ;

    @Column(name="update_by", length=45)
    private String     updateBy     ;

    @Temporal(TemporalType.DATE)
    @Column(name="update_date")
    private Date       updateDate   ;

	// "typeId" (column "type_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="type_id", referencedColumnName="id")
    private ProductType productType ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Product() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : create_by ( varchar ) 
    public void setCreateBy( String createBy ) {
        this.createBy = createBy;
    }
    public String getCreateBy() {
        return this.createBy;
    }

    //--- DATABASE MAPPING : create_date ( date ) 
    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- DATABASE MAPPING : prod_brand ( varchar ) 
    public void setProdBrand( String prodBrand ) {
        this.prodBrand = prodBrand;
    }
    public String getProdBrand() {
        return this.prodBrand;
    }

    //--- DATABASE MAPPING : prod_code ( varchar ) 
    public void setProdCode( String prodCode ) {
        this.prodCode = prodCode;
    }
    public String getProdCode() {
        return this.prodCode;
    }

    //--- DATABASE MAPPING : prod_color ( varchar ) 
    public void setProdColor( String prodColor ) {
        this.prodColor = prodColor;
    }
    public String getProdColor() {
        return this.prodColor;
    }

    //--- DATABASE MAPPING : prod_desc ( varchar ) 
    public void setProdDesc( String prodDesc ) {
        this.prodDesc = prodDesc;
    }
    public String getProdDesc() {
        return this.prodDesc;
    }

    //--- DATABASE MAPPING : prod_img ( varchar ) 
    public void setProdImg( String prodImg ) {
        this.prodImg = prodImg;
    }
    public String getProdImg() {
        return this.prodImg;
    }

    //--- DATABASE MAPPING : prod_model ( varchar ) 
    public void setProdModel( String prodModel ) {
        this.prodModel = prodModel;
    }
    public String getProdModel() {
        return this.prodModel;
    }

    //--- DATABASE MAPPING : prod_name ( varchar ) 
    public void setProdName( String prodName ) {
        this.prodName = prodName;
    }
    public String getProdName() {
        return this.prodName;
    }

    //--- DATABASE MAPPING : prod_price ( int8 ) 
    public void setProdPrice( Long prodPrice ) {
        this.prodPrice = prodPrice;
    }
    public Long getProdPrice() {
        return this.prodPrice;
    }

    //--- DATABASE MAPPING : prod_quantity ( int4 ) 
    public void setProdQuantity( Integer prodQuantity ) {
        this.prodQuantity = prodQuantity;
    }
    public Integer getProdQuantity() {
        return this.prodQuantity;
    }

    //--- DATABASE MAPPING : prod_status ( int4 ) 
    public void setProdStatus( Integer prodStatus ) {
        this.prodStatus = prodStatus;
    }
    public Integer getProdStatus() {
        return this.prodStatus;
    }

    //--- DATABASE MAPPING : update_by ( varchar ) 
    public void setUpdateBy( String updateBy ) {
        this.updateBy = updateBy;
    }
    public String getUpdateBy() {
        return this.updateBy;
    }

    //--- DATABASE MAPPING : update_date ( date ) 
    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setProductType( ProductType productType ) {
        this.productType = productType;
    }
    public ProductType getProductType() {
        return this.productType;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(createBy);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(prodBrand);
        sb.append("|");
        sb.append(prodCode);
        sb.append("|");
        sb.append(prodColor);
        sb.append("|");
        sb.append(prodDesc);
        sb.append("|");
        sb.append(prodImg);
        sb.append("|");
        sb.append(prodModel);
        sb.append("|");
        sb.append(prodName);
        sb.append("|");
        sb.append(prodPrice);
        sb.append("|");
        sb.append(prodQuantity);
        sb.append("|");
        sb.append(prodStatus);
        sb.append("|");
        sb.append(updateBy);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 

}
