/*
 * Created on 7 Apr 2016 ( Time 00:39:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.tsm.project.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "stockcheck"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="stockcheck", schema="main" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Stockcheck.countAll", query="SELECT COUNT(x) FROM Stockcheck x" )
} )
public class Stockcheck implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="checkId", nullable=false)
    private Integer    checkid      ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="prodAmount")
    private Integer    prodamount   ;

    @Column(name="count")
    private Integer    count        ;

    @Column(name="checkCode", length=100)
    private String     checkcode    ;

    @Column(name="detail", length=250)
    private String     detail       ;

    @Column(name="logStatus")
    private Integer    logstatus    ;

    @Temporal(TemporalType.DATE)
    @Column(name="createDate")
    private Date       createdate   ;

    @Column(name="createBy", length=100)
    private String     createby     ;

	// "productid" (column "productId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="productId", referencedColumnName="id")
    private Product product     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Stockcheck()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCheckid( Integer checkid )
    {
        this.checkid = checkid ;
    }
    public Integer getCheckid()
    {
        return this.checkid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : prodAmount ( int4 ) 
    public void setProdamount( Integer prodamount )
    {
        this.prodamount = prodamount;
    }
    public Integer getProdamount()
    {
        return this.prodamount;
    }

    //--- DATABASE MAPPING : count ( int4 ) 
    public void setCount( Integer count )
    {
        this.count = count;
    }
    public Integer getCount()
    {
        return this.count;
    }

    //--- DATABASE MAPPING : checkCode ( bpchar ) 
    public void setCheckcode( String checkcode )
    {
        this.checkcode = checkcode;
    }
    public String getCheckcode()
    {
        return this.checkcode;
    }

    //--- DATABASE MAPPING : detail ( bpchar ) 
    public void setDetail( String detail )
    {
        this.detail = detail;
    }
    public String getDetail()
    {
        return this.detail;
    }

    //--- DATABASE MAPPING : logStatus ( int4 ) 
    public void setLogstatus( Integer logstatus )
    {
        this.logstatus = logstatus;
    }
    public Integer getLogstatus()
    {
        return this.logstatus;
    }

    //--- DATABASE MAPPING : createDate ( date ) 
    public void setCreatedate( Date createdate )
    {
        this.createdate = createdate;
    }
    public Date getCreatedate()
    {
        return this.createdate;
    }

    //--- DATABASE MAPPING : createBy ( bpchar ) 
    public void setCreateby( String createby )
    {
        this.createby = createby;
    }
    public String getCreateby()
    {
        return this.createby;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setProduct( Product product )
    {
        this.product = product;
    }
    public Product getProduct()
    {
        return this.product;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(checkid);
        sb.append("]:"); 
        sb.append(prodamount);
        sb.append("|");
        sb.append(count);
        sb.append("|");
        sb.append(checkcode);
        sb.append("|");
        sb.append(detail);
        sb.append("|");
        sb.append(logstatus);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(createby);
        return sb.toString(); 
    } 

}