/*
 * Created on 7 Apr 2016 ( Time 00:39:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.tsm.project.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "stockhistorylog"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="stockhistorylog", schema="main" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Stockhistorylog.countAll", query="SELECT COUNT(x) FROM Stockhistorylog x" )
} )
public class Stockhistorylog implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="logId", nullable=false)
    private Integer    logid        ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="amount")
    private Integer    amount       ;

    @Column(name="detail", length=250)
    private String     detail       ;

    @Column(name="lotNo", length=100)
    private String     lotno        ;

    @Temporal(TemporalType.DATE)
    @Column(name="operationdate")
    private Date       operationdate ;

    @Column(name="logType")
    private Integer    logtype      ;

    @Column(name="createBy", length=100)
    private String     createby     ;

    @Temporal(TemporalType.DATE)
    @Column(name="createDate")
    private Date       createdate   ;

	// "productid" (column "productId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="productId", referencedColumnName="id")
    private Product product     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Stockhistorylog()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setLogid( Integer logid )
    {
        this.logid = logid ;
    }
    public Integer getLogid()
    {
        return this.logid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : amount ( int4 ) 
    public void setAmount( Integer amount )
    {
        this.amount = amount;
    }
    public Integer getAmount()
    {
        return this.amount;
    }

    //--- DATABASE MAPPING : detail ( bpchar ) 
    public void setDetail( String detail )
    {
        this.detail = detail;
    }
    public String getDetail()
    {
        return this.detail;
    }

    //--- DATABASE MAPPING : lotNo ( bpchar ) 
    public void setLotno( String lotno )
    {
        this.lotno = lotno;
    }
    public String getLotno()
    {
        return this.lotno;
    }

    //--- DATABASE MAPPING : operationdate ( date ) 
    public void setOperationdate( Date operationdate )
    {
        this.operationdate = operationdate;
    }
    public Date getOperationdate()
    {
        return this.operationdate;
    }

    //--- DATABASE MAPPING : logType ( int4 ) 
    public void setLogtype( Integer logtype )
    {
        this.logtype = logtype;
    }
    public Integer getLogtype()
    {
        return this.logtype;
    }

    //--- DATABASE MAPPING : createBy ( bpchar ) 
    public void setCreateby( String createby )
    {
        this.createby = createby;
    }
    public String getCreateby()
    {
        return this.createby;
    }

    //--- DATABASE MAPPING : createDate ( date ) 
    public void setCreatedate( Date createdate )
    {
        this.createdate = createdate;
    }
    public Date getCreatedate()
    {
        return this.createdate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setProduct( Product product )
    {
        this.product = product;
    }
    public Product getProduct()
    {
        return this.product;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(logid);
        sb.append("]:"); 
        sb.append(amount);
        sb.append("|");
        sb.append(detail);
        sb.append("|");
        sb.append(lotno);
        sb.append("|");
        sb.append(operationdate);
        sb.append("|");
        sb.append(logtype);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(createdate);
        return sb.toString(); 
    } 

}